Added leaderboard link to desktop and mobile menu
DetektivKollektiv/angular-ui pull request #233
Opened 2022-05-25 10:17 UTC by PotSchmoell

2022-05-25 10:23 UTC, SandroGlueck requested changes

2022-05-25 10:23 UTC, SandroGlueck commented on src/app/core/components/header/header.component.html
> +                  <a class="navigation-flyout__link" title="Profil" [routerLink]="['/leaderboard']">Rangliste</a>
`title` solltest noch anpassen. Das wird oft als Tooltip angezeigt.

2022-05-25 10:23 UTC, SandroGlueck commented on src/app/core/dialogs/menu-dialog/menu-dialog.component.html
> +            <a title="Profil" (click)="navigate('/leaderboard')">Rangliste</a>
Hier auch `title`

2022-05-25 12:49 UTC, PotSchmoell commented on src/app/core/components/header/header.component.html
> +                  <a class="navigation-flyout__link" title="Profil" [routerLink]="['/leaderboard']">Rangliste</a>
Da war ich wohl ein bisschen voreilig. Danke!

2022-06-01 17:39 UTC, SandroGlueck approved these changes

2022-06-01 17:47 UTC, merged